// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TDK.Infrastructure.Data;

#nullable disable

namespace TDK.Infrastructure.Migrations
{
    [DbContext(typeof(TdkDbContext))]
    [Migration("20260920113341_BookingOperations")]
    partial class BookingOperations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TDK.Domain.Entities.Booking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("ReminderSentAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingReference")
                        .IsUnique();

                    b.HasIndex("CourtId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TDK.Domain.Entities.Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Courts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CloseTime = new TimeOnly(0, 0, 0),
                            CreatedAt = new DateTime(2026, 9, 20, 11, 33, 40, 182, DateTimeKind.Utc).AddTicks(267),
                            DisplayName = "Court 1",
                            IsActive = true,
                            Name = "Court 1",
                            OpenTime = new TimeOnly(7, 0, 0),
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2026, 9, 20, 11, 33, 40, 182, DateTimeKind.Utc).AddTicks(272)
                        },
                        new
                        {
                            Id = 2,
                            CloseTime = new TimeOnly(0, 0, 0),
                            CreatedAt = new DateTime(2026, 9, 20, 11, 33, 40, 182, DateTimeKind.Utc).AddTicks(277),
                            DisplayName = "Court 2",
                            IsActive = true,
                            Name = "Court 2",
                            OpenTime = new TimeOnly(7, 0, 0),
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2026, 9, 20, 11, 33, 40, 182, DateTimeKind.Utc).AddTicks(278)
                        });
                });

            modelBuilder.Entity("TDK.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TDK.Domain.Entities.Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("PricePerHour")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Rates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 20, 11, 33, 40, 183, DateTimeKind.Utc).AddTicks(3558),
                            EndTime = new TimeOnly(17, 0, 0),
                            IsActive = true,
                            PricePerHour = 320m,
                            StartTime = new TimeOnly(7, 0, 0),
                            UpdatedAt = new DateTime(2026, 9, 20, 11, 33, 40, 183, DateTimeKind.Utc).AddTicks(3565)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 20, 11, 33, 40, 183, DateTimeKind.Utc).AddTicks(3569),
                            EndTime = new TimeOnly(0, 0, 0),
                            IsActive = true,
                            PricePerHour = 400m,
                            StartTime = new TimeOnly(17, 0, 0),
                            UpdatedAt = new DateTime(2026, 9, 20, 11, 33, 40, 183, DateTimeKind.Utc).AddTicks(3571)
                        });
                });

            modelBuilder.Entity("TDK.Domain.Entities.Schedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("ScheduleDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("TimeSlotId");

                    b.HasIndex("CourtId", "ScheduleDate", "TimeSlotId")
                        .IsUnique();

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("TDK.Domain.Entities.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "07:00 - 08:00",
                            EndTime = new TimeOnly(8, 0, 0),
                            IsActive = true,
                            SortOrder = 1,
                            StartTime = new TimeOnly(7, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "08:00 - 09:00",
                            EndTime = new TimeOnly(9, 0, 0),
                            IsActive = true,
                            SortOrder = 2,
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "09:00 - 10:00",
                            EndTime = new TimeOnly(10, 0, 0),
                            IsActive = true,
                            SortOrder = 3,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            DisplayName = "10:00 - 11:00",
                            EndTime = new TimeOnly(11, 0, 0),
                            IsActive = true,
                            SortOrder = 4,
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            DisplayName = "11:00 - 12:00",
                            EndTime = new TimeOnly(12, 0, 0),
                            IsActive = true,
                            SortOrder = 5,
                            StartTime = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            DisplayName = "12:00 - 13:00",
                            EndTime = new TimeOnly(13, 0, 0),
                            IsActive = true,
                            SortOrder = 6,
                            StartTime = new TimeOnly(12, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            DisplayName = "13:00 - 14:00",
                            EndTime = new TimeOnly(14, 0, 0),
                            IsActive = true,
                            SortOrder = 7,
                            StartTime = new TimeOnly(13, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            DisplayName = "14:00 - 15:00",
                            EndTime = new TimeOnly(15, 0, 0),
                            IsActive = true,
                            SortOrder = 8,
                            StartTime = new TimeOnly(14, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            DisplayName = "15:00 - 16:00",
                            EndTime = new TimeOnly(16, 0, 0),
                            IsActive = true,
                            SortOrder = 9,
                            StartTime = new TimeOnly(15, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            DisplayName = "16:00 - 17:00",
                            EndTime = new TimeOnly(17, 0, 0),
                            IsActive = true,
                            SortOrder = 10,
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            Id = 11,
                            DisplayName = "17:00 - 18:00",
                            EndTime = new TimeOnly(18, 0, 0),
                            IsActive = true,
                            SortOrder = 11,
                            StartTime = new TimeOnly(17, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            DisplayName = "18:00 - 19:00",
                            EndTime = new TimeOnly(19, 0, 0),
                            IsActive = true,
                            SortOrder = 12,
                            StartTime = new TimeOnly(18, 0, 0)
                        },
                        new
                        {
                            Id = 13,
                            DisplayName = "19:00 - 20:00",
                            EndTime = new TimeOnly(20, 0, 0),
                            IsActive = true,
                            SortOrder = 13,
                            StartTime = new TimeOnly(19, 0, 0)
                        },
                        new
                        {
                            Id = 14,
                            DisplayName = "20:00 - 21:00",
                            EndTime = new TimeOnly(21, 0, 0),
                            IsActive = true,
                            SortOrder = 14,
                            StartTime = new TimeOnly(20, 0, 0)
                        },
                        new
                        {
                            Id = 15,
                            DisplayName = "21:00 - 22:00",
                            EndTime = new TimeOnly(22, 0, 0),
                            IsActive = true,
                            SortOrder = 15,
                            StartTime = new TimeOnly(21, 0, 0)
                        },
                        new
                        {
                            Id = 16,
                            DisplayName = "22:00 - 23:00",
                            EndTime = new TimeOnly(23, 0, 0),
                            IsActive = true,
                            SortOrder = 16,
                            StartTime = new TimeOnly(22, 0, 0)
                        },
                        new
                        {
                            Id = 17,
                            DisplayName = "23:00 - 00:00",
                            EndTime = new TimeOnly(0, 0, 0),
                            IsActive = true,
                            SortOrder = 17,
                            StartTime = new TimeOnly(23, 0, 0)
                        });
                });

            modelBuilder.Entity("TDK.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TDK.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TDK.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TDK.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TDK.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TDK.Domain.Entities.Booking", b =>
                {
                    b.HasOne("TDK.Domain.Entities.Court", "Court")
                        .WithMany("Bookings")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Court");
                });

            modelBuilder.Entity("TDK.Domain.Entities.Notification", b =>
                {
                    b.HasOne("TDK.Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("TDK.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("TDK.Domain.Entities.Booking", "Booking")
                        .WithMany("Schedules")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TDK.Domain.Entities.Court", "Court")
                        .WithMany("Schedules")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDK.Domain.Entities.TimeSlot", "TimeSlot")
                        .WithMany("Schedules")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Court");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("TDK.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("TDK.Domain.Entities.Court", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("TDK.Domain.Entities.TimeSlot", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
